spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to VCB accounts related qa APIs "
  contactDetails:
    name: "HNT - Developer"
    email: "hnt@guru.com"
  onCallSupport:
    - (999) 555-1234
    - (999) 523-1345
