services:
  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    image: "hnt/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    image: "hnt/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    image: "hnt/accounts:s9"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    image: "hnt/loans:s9"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    image: "hnt/cards:s9"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
networks:
  bridgeNetwork:
    driver: "bridge"