spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
encrypt:
  key: "spring-microservices-2024"

server:
  port: 8071
