services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    image: "hnt/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bridgeNetwork
  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    image: "hnt/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bridgeNetwork
  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    image: "hnt/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bridgeNetwork
networks:
  bridgeNetwork:
    driver: "bridge"